### PR TITLE
changes on Capture Screenshot button look and make the screenshot ima…

### PR DESCRIPTION
**Pull request by thisisakshatsri**
Add a image icon in "Capture Screenshot button" and centre screenshot image in container ( prev - the image doesn't look on the centre).

### CODE REVIEW

**Comment by ykdojo** [comment]
#30

**Comment by ykdojo** [comment]
Looks like there's a conflict now. I'll wait for a week to see if there's any update.

**Comment by thisisakshatsri** [comment]
Hi YK, that's my first contribution to an open source project. Can you please help me to know what's wrong !

**Comment by ykdojo** [comment]
The biggest thing is that this was nothing that was in an issue.

**Pull request closed without merging**
