### PR TITLE
Switch to plasmo + react

### PR DESCRIPTION
**Pull request by omar-shahid**
## Adresses
- #20 
- #26

## Description
- Initliazed Plasmo + React 
- Migrated example screenshot code from vanilla JS to Plasmo + React
- Entry point is now: `popup.tsx`

## Preview
image

### CODE REVIEW

**Comment by ykdojo** [comment]
Thank you. No change in the installation instructions in README?

**Comment by ykdojo** [comment]
Also a note on how to go about further developing this in README would be helpful.

**Comment by omar-shahid** [comment]
@ykdojo done

**Comment by ykdojo** [comment]
Thank you!

Created #32 for a more thorough review.

**Pull request merged**
